# Generated by Django 4.2.11 on 2024-04-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('location', models.CharField(max_length=50, verbose_name='Локация')),
                ('service_type', models.CharField(max_length=50, verbose_name='Тип сервиса')),
                ('info', models.TextField(verbose_name='Информация')),
                ('date', models.DateTimeField(verbose_name='Дата контакта')),
            ],
        ),
    ]
