# Generated by Django 4.2.11 on 2024-05-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artiles',
            options={'verbose_name': 'Форма обратной связи', 'verbose_name_plural': 'Формы обратной связи'},
        ),
        migrations.RenameField(
            model_name='artiles',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='artiles',
            name='location',
        ),
        migrations.AddField(
            model_name='artiles',
            name='last_name',
            field=models.CharField(default='NO LAST NAME', max_length=50, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='artiles',
            name='service_type',
            field=models.CharField(choices=[('Taxi', 'Taxi'), ('Delivery', 'Delivery')], default='Taxi', max_length=20),
        ),
    ]
