# Generated by Django 4.2.11 on 2024-05-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_artiles_options_rename_name_artiles_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='artiles',
            name='service_type',
            field=models.CharField(choices=[('Ride hailing', 'Ride hailing'), ('Taxi', 'Taxi'), ('Executive cars', 'Executive cars'), ('Aiport shuttle', 'Aiport shuttle'), ('Bikes or motorbikes', 'Bikes or motorbikes'), ('Delivery', 'Delivery'), ('Other', 'Other')], default='Taxi', max_length=20),
        ),
    ]
