# Generated by Django 4.2.11 on 2024-05-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_artiles_last_name_alter_artiles_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='info',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Google', 'Google'), ('Online media', 'Online media'), ('Other social media', 'Other social media'), ('Referred by customer', 'Referred by customer'), ('Delivery', 'Delivery'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='artiles',
            name='service_type',
            field=models.CharField(choices=[('Ride hailing', 'Ride hailing'), ('Taxi', 'Taxi'), ('Executive cars', 'Executive cars'), ('Aiport shuttle', 'Aiport shuttle'), ('Bikes or motorbikes', 'Bikes or motorbikes'), ('Delivery', 'Delivery'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Имя пользователя'),
        ),
    ]
