# Generated by Django 4.2.11 on 2024-05-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_alter_artiles_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artiles',
            name='date',
        ),
    ]
