# Generated by Django 5.0.6 on 2024-05-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_remove_artiles_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('service_type', models.CharField(choices=[('Ride hailing', 'Ride hailing'), ('Taxi', 'Taxi'), ('Executive cars', 'Executive cars'), ('Aiport shuttle', 'Aiport shuttle'), ('Bikes or motorbikes', 'Bikes or motorbikes'), ('Delivery', 'Delivery'), ('Other', 'Other')], default='Other', max_length=20)),
                ('info', models.CharField(choices=[('Facebook', 'Facebook'), ('Google', 'Google'), ('Online media', 'Online media'), ('Other social media', 'Other social media'), ('Referred by customer', 'Referred by customer'), ('Delivery', 'Delivery'), ('Other', 'Other')], default='Other', max_length=20)),
                ('mark_communication', models.BooleanField(default='false')),
                ('personalize_ads', models.BooleanField(default='false')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Формы обратной связи',
            },
        ),
        migrations.DeleteModel(
            name='Artiles',
        ),
    ]
