# Generated by Django 5.0.6 on 2024-05-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_feedback_delete_artiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mark_communication',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='personalize_ads',
            field=models.BooleanField(default=False),
        ),
    ]
